"""Agent Runtime persistence ports."""

from typing import Protocol
from uuid import UUID

from app.domain.agent_runtime import (
    AgentApproval,
    AgentCheckpoint,
    AgentRun,
    AgentToolCall,
)


class AgentRuntimeRepository(Protocol):
    async def add_run(self, run: AgentRun) -> AgentRun: ...

    async def get_run(self, run_id: UUID) -> AgentRun | None: ...

    async def update_run(self, run: AgentRun) -> AgentRun: ...

    async def add_tool_call(self, tool_call: AgentToolCall) -> AgentToolCall: ...

    async def update_tool_call(self, tool_call: AgentToolCall) -> AgentToolCall: ...

    async def list_tool_calls(self, run_id: UUID) -> list[AgentToolCall]: ...

    async def add_approval(self, approval: AgentApproval) -> AgentApproval: ...

    async def get_approval(self, approval_id: UUID) -> AgentApproval | None: ...

    async def get_pending_approval(self, run_id: UUID) -> AgentApproval | None: ...

    async def get_latest_approval(self, run_id: UUID) -> AgentApproval | None: ...

    async def update_approval(self, approval: AgentApproval) -> AgentApproval: ...

    async def add_checkpoint(self, checkpoint: AgentCheckpoint) -> AgentCheckpoint: ...

    async def get_latest_checkpoint(self, run_id: UUID) -> AgentCheckpoint | None: ...

    async def delete_checkpoints(self, run_id: UUID) -> None: ...

    async def commit(self) -> None: ...


__all__ = ("AgentRuntimeRepository",)
