"""Decision & Reporting 应用层依赖的 Repository 契约。"""

from typing import Protocol
from uuid import UUID

from app.domain.decision import CompanyAssessment, DecisionCase, DecisionReport, JobFitAnalysis


class DecisionCaseRepository(Protocol):
    """用户范围内 DecisionCase 的幂等创建、生命周期更新与读取端口。"""

    async def add(self, decision_case: DecisionCase) -> DecisionCase: ...

    async def update(self, decision_case: DecisionCase) -> DecisionCase: ...

    async def get_by_id(self, case_id: UUID) -> DecisionCase | None: ...

    async def get_by_input_fingerprint(self, fingerprint: str) -> DecisionCase | None: ...

    async def commit(self) -> None: ...


class DecisionReportRepository(Protocol):
    """用户范围内不可变 DecisionReport 的版本化持久化端口。"""

    async def next_version(self, decision_case_id: UUID) -> int: ...

    async def add(self, report: DecisionReport) -> DecisionReport: ...

    async def get_by_generation(
        self,
        decision_case_id: UUID,
        rule_set_version: str,
        generator_version: str,
    ) -> DecisionReport | None: ...

    async def get_by_id(self, report_id: UUID) -> DecisionReport | None: ...

    async def list_for_case(self, decision_case_id: UUID) -> list[DecisionReport]: ...

    async def list(self, *, offset: int, limit: int) -> list[DecisionReport]: ...

    async def count(self) -> int: ...

    async def commit(self) -> None: ...


class JobFitAnalysisRepository(Protocol):
    """User-scoped immutable AI job-fit analysis storage."""

    async def next_version(self, report_id: UUID) -> int: ...

    async def add(self, analysis: JobFitAnalysis) -> JobFitAnalysis: ...

    async def get_by_generation(self, generation_identity: str) -> JobFitAnalysis | None: ...

    async def get_for_report(self, report_id: UUID) -> JobFitAnalysis | None: ...

    async def commit(self) -> None: ...


class CompanyAssessmentRepository(Protocol):
    """User-scoped fixed company attachment storage."""

    async def add(self, assessment: CompanyAssessment) -> CompanyAssessment: ...

    async def get_by_generation(self, generation_identity: str) -> CompanyAssessment | None: ...

    async def get_for_report(self, report_id: UUID) -> CompanyAssessment | None: ...

    async def commit(self) -> None: ...
