from typing import Protocol
from uuid import UUID

from app.domain.followup import InterviewPreparation


class InterviewPreparationRepository(Protocol):
    async def next_version(self, interview_case_id: UUID) -> int: ...
    async def add(self, preparation: InterviewPreparation) -> InterviewPreparation: ...
    async def get_latest(self, interview_case_id: UUID) -> InterviewPreparation | None: ...
    async def get_version(
        self, interview_case_id: UUID, version: int
    ) -> InterviewPreparation | None: ...
    async def list_versions(self, interview_case_id: UUID) -> list[InterviewPreparation]: ...
    async def commit(self) -> None: ...
