"""Export Nora's deterministic OpenAPI contract for frontend generation."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from app.apps.api import create_app
from app.infrastructure.config import Settings

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = REPOSITORY_ROOT / "frontend" / "src" / "api" / "generated" / "openapi.json"
GENERATED_NOTICE = "Generated by backend/scripts/export_openapi.py; DO NOT EDIT."


def build_openapi_document() -> dict[str, Any]:
    """Build the schema without reading Nora runtime environment variables."""

    settings = Settings(_env_file=None, _env_prefix="NORA_OPENAPI_EXPORT_")
    document = create_app(settings).openapi()
    document["x-generated-notice"] = GENERATED_NOTICE
    return document


def render_openapi(document: dict[str, Any]) -> bytes:
    """Serialize the schema using Nora's stable generated-file contract."""

    rendered = json.dumps(
        document,
        ensure_ascii=False,
        allow_nan=False,
        indent=2,
        sort_keys=True,
    )
    return f"{rendered}\n".encode()


def export_openapi(output: Path = DEFAULT_OUTPUT) -> bytes:
    """Write and return the canonical OpenAPI bytes."""

    content = render_openapi(build_openapi_document())
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_bytes(content)
    return content


def main() -> None:
    """Export the frontend contract to its repository-owned location."""

    export_openapi()
    print(DEFAULT_OUTPUT.relative_to(REPOSITORY_ROOT))


if __name__ == "__main__":
    main()
